# Generated by Django 3.2.4 on 2021-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('keyword', models.TextField(null=True)),
                ('userid', models.CharField(max_length=255)),
            ],
        ),
    ]
